### ISSUE TITLE
Core dump on exiting app

### ISSUE THREAD

**Issue by elysia-best** [LingmoOS/lingmo-settings#24]
```
warning: 44     ./nptl/pthread_kill.c: 没有那个文件或目录
[Current thread is 1 (Thread 0x7f292c6c2d00 (LWP 162551))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f292f2a347f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f292f254532 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f292f23d4ed in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f292f8922cb in QMessageLogger::fatal(char const*, ...) const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f292fee9a70 in ??? () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#6  0x00007f292ffcfa18 in QPixmap::QPixmap() () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007f292ff552a7 in QCursor::QCursor(Qt::CursorShape) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007f292ff51128 in QWindowPrivate::setCursor(QCursor const*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007f292a65ca07 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#10 0x00007f292a65c7f5 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#11 0x00007f292a65c7f5 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#12 0x00007f292a65c7f5 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#13 0x00007f292a65c7f5 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#14 0x00007f292a65c7f5 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#15 0x00007f292a76a345 in QQuickShaderEffectSource::itemChange(QQuickItem::ItemChange, QQuickItem::ItemChangeData const&) () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#16 0x00007f292a65c84f in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#17 0x00007f292a7721a9 in QQuickOpenGLShaderEffectCommon::updateWindow(QQuickWindow*) () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#18 0x00007f292a76c975 in QQuickShaderEffect::itemChange(QQuickItem::ItemChange, QQuickItem::ItemChangeData const&) () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#19 0x00007f292a65c84f in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#20 0x00007f292a65c7f5 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#21 0x00007f292a65c7f5 in QQuickItemPrivate::derefWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#22 0x00007f292a65d6ee in QQuickItem::~QQuickItem() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#23 0x00007f292a67ee75 in ??? () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#24 0x00007f292a674080 in QQuickWindow::~QQuickWindow() () at /lib/x86_64-linux-gnu/libQt5Quick.so.5
#25 0x00007f292b65641d in ??? () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Window.2/libwindowplugin.so
#26 0x00007f29308f6a6e in QQmlApplicationEnginePrivate::cleanUp() () at /lib/x86_64-linux-gnu/libQt5Qml.so.5
#27 0x00007f29308f6abc in QQmlApplicationEngine::~QQmlApplicationEngine() () at /lib/x86_64-linux-gnu/libQt5Qml.so.5
#28 0x000055e52f6fbd13 in Application::~Application (this=0x7ffd4efd5960, __in_chrg=<optimized out>) at ./src/application.h:11
#29 main (argc=<optimized out>, argv=<optimized out>) at ./src/main.cpp:51
```

**Comment by arkimium** [comment]
You may need to check whether the **Qt Library** is broken or debug the code now.

**Comment by arkimium** [comment]
The information shows that your **QtQCT has been crashed.** Try _Debugger_?

**Comment by arkimium** [comment]
> The information shows that your **QtQCT has been crashed.** Try _Debugger_?

I found that you cannot found the bug from debugger. So does the Qt Library is crashed?

**Comment by elysia-best** [comment]
> > The information shows that your **QtQCT has been crashed.** Try _Debugger_?
> 
> I found that you cannot found the bug from debugger. So does the Qt Library is crashed?

Yes! This happened when this app existed. I need Qt's debug symbol to debug it.

Meanwhile, it seems that the bug may be in the QML part rather than C++ part.

**Comment by arkimium** [comment]
> > > The information shows that your **QtQCT has been crashed.** Try _Debugger_?
> > 
> > I found that you cannot found the bug from debugger. So does the Qt Library is crashed?
> 
> Yes! This happened when this app existed. I need Qt's debug symbol to debug it.
> 
> Meanwhile, it seems that the bug may be in the QML part rather than C++ part.

Then try to debug QML part? Or switch to **Qt6**?

**Comment by elysia-best** [comment]
This is now fixed! Thanks for all the advise.
